version: '3'

services:
  iot-backend:
    container_name: iot-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db

  db:
    image: postgres
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - ./data1:/var/lib/postgresql/data
    ports:
      - 5432:5432
 